function UIStatusSwitch(close, handles)
global UiStatus;
if(close == 1)
    UiStatus.SourceVideoButtonEnable = get(handles.SourceVideoButton, 'Enable');
    UiStatus.SourceMatteButtonEnable = get(handles.SourceMatteButton, 'Enable');
    UiStatus.OpenSourceMatteEnable = get(handles.OpenSourceMatte, 'Enable');
    UiStatus.SourceSynEnable = get(handles.SourceSyn, 'Enable');
    UiStatus.TargetVideoButtonEnable = get(handles.TargetVideoButton, 'Enable');
    UiStatus.TargetMatteButtonEnable = get(handles.TargetMatteButton, 'Enable');
    UiStatus.BackVideoEnable = get(handles.BackVideo, 'Enable');
    UiStatus.TargetBackMatteEnable = get(handles.TargetBackMatte, 'Enable');
    UiStatus.OpenTargetMatteEnable = get(handles.OpenTargetMatte, 'Enable');
    UiStatus.OpenBackMatteEnable = get(handles.OpenBackMatte, 'Enable');
    UiStatus.TargetSynEnable = get(handles.TargetSyn, 'Enable');
    UiStatus.UpdateForeKeyframesEnable = get(handles.UpdateForeKeyframes, 'Enable');
    UiStatus.UpdateBackKeyframesEnable = get(handles.UpdateBackKeyframes, 'Enable');
    UiStatus.OpenFilter = get(handles.OpenFilter, 'Enable');
    UiStatus.OpenForeMatteReverse = get(handles.OpenForeMatteReverse, 'Enable');
    UiStatus.OpenBackMatteReverse = get(handles.OpenBackMatteReverse, 'Enable');
    UiStatus.SourceMatte = get(handles.SourceMatte, 'Enable');
    UiStatus.TargetForeMatte = get(handles.TargetForeMatte, 'Enable');
    UiStatus.TargetBackTag = get(handles.TargetBackTag, 'Enable');
    UiStatus.TargetBackMatteTag = get(handles.TargetBackMatteTag, 'Enable');
    UiStatus.OutputSourceVideo = get(handles.OutputSourceVideo, 'Enable');
    UiStatus.OutputSourceForeVideo = get(handles.OutputSourceForeVideo, 'Enable');
    UiStatus.OutputSourceBackVideo = get(handles.OutputSourceBackVideo, 'Enable');
    UiStatus.OutputLuminaVideo = get(handles.OutputLuminaVideo, 'Enable');
    UiStatus.OutputChrominaVideo = get(handles.OutputChrominaVideo, 'Enable');
    UiStatus.OutputSyncVideo = get(handles.OutputSyncVideo, 'Enable');
    UiStatus.OutputForeLuminaVideo = get(handles.OutputForeLuminaVideo, 'Enable');
    UiStatus.OutputForeChrominaVideo = get(handles.OutputForeChrominaVideo, 'Enable');
    UiStatus.OutputForeSyncVideo = get(handles.OutputForeSyncVideo, 'Enable');
    UiStatus.OutputForeLumWholeVideo = get(handles.OutputForeLumWholeVideo, 'Enable');
    UiStatus.OutputForeChroWholeVideo = get(handles.OutputForeChroWholeVideo, 'Enable');
    UiStatus.OutputForeSyncWholeVideo = get(handles.OutputForeSyncWholeVideo, 'Enable');
    UiStatus.OutputBackLuminaVideo = get(handles.OutputBackLuminaVideo, 'Enable');
    UiStatus.OutputBackChrominaVideo = get(handles.OutputBackChrominaVideo, 'Enable');
    UiStatus.OutputBackSyncVideo = get(handles.OutputBackSyncVideo, 'Enable');
    UiStatus.OutputBackLumWholeVideo = get(handles.OutputBackLumWholeVideo, 'Enable');
    UiStatus.OutputBackChroWholeVideo = get(handles.OutputBackChroWholeVideo, 'Enable');
    UiStatus.OutputBackSyncWholeVideo = get(handles.OutputBackSyncWholeVideo, 'Enable');
    UiStatus.TargetForeSlices = get(handles.TargetForeSlices, 'Enable');
    UiStatus.TargetForeMatteSlices = get(handles.TargetForeMatteSlices, 'Enable');
    UiStatus.TargetBackSlices = get(handles.TargetBackSlices, 'Enable');
    UiStatus.TargetBackMatteSlices = get(handles.TargetBackMatteSlices, 'Enable');
    UiStatus.SplitVideo = get(handles.SplitVideo, 'Enable');
    UiStatus.Recombine = get(handles.Recombine, 'Enable');
    % 锁定UI为非使能态.
    set(handles.SourceVideoButton, 'Enable', 'off');
    set(handles.SourceMatteButton, 'Enable', 'off');
    set(handles.OpenSourceMatte, 'Enable', 'off');
    set(handles.SourceSyn, 'Enable', 'off');
    set(handles.TargetVideoButton, 'Enable', 'off');
    set(handles.TargetMatteButton, 'Enable', 'off');
    set(handles.BackVideo, 'Enable', 'off');
    set(handles.TargetBackMatte, 'Enable', 'off');
    set(handles.OpenTargetMatte, 'Enable', 'off');
    set(handles.OpenBackMatte, 'Enable', 'off');
    set(handles.TargetSyn, 'Enable', 'off');
    set(handles.UpdateForeKeyframes, 'Enable', 'off');
    set(handles.UpdateBackKeyframes, 'Enable', 'off');
    set(handles.OpenFilter, 'Enable', 'off');
    set(handles.OpenForeMatteReverse, 'Enable', 'off');
    set(handles.OpenBackMatteReverse, 'Enable', 'off');
    set(handles.SourceMatte, 'Enable', 'off');
    set(handles.TargetForeMatte, 'Enable', 'off');
    set(handles.TargetBackTag, 'Enable','off');
    set(handles.TargetBackMatteTag, 'Enable', 'off');
    set(handles.SourceVideoMenu, 'Enable', 'off');
    set(handles.LeftAddVideoButton, 'Enable', 'off');
    set(handles.LeftPlay, 'Enable', 'off');
    set(handles.CloseLeft, 'Enable', 'off');
    set(handles.LeftKeyFrames, 'Enable', 'off');
    set(handles.RightPlay, 'Enable', 'off');
    set(handles.CloseRight, 'Enable', 'off');
    set(handles.RightKeyFrames, 'Enable', 'off');
    set(handles.TargetVideoMenu, 'Enable', 'off');
    set(handles.RightAddVideoButton, 'Enable', 'off');
    set(handles.SourceTag, 'Enable', 'off');
    set(handles.TargetForeTag, 'Enable', 'off');
    set(handles.OutputSourceVideo, 'Enable', 'off');
    set(handles.OutputSourceForeVideo, 'Enable', 'off');
    set(handles.OutputSourceBackVideo, 'Enable', 'off');
    set(handles.OutputLuminaVideo, 'Enable', 'off');
    set(handles.OutputChrominaVideo, 'Enable', 'off');
    set(handles.OutputSyncVideo, 'Enable', 'off');
    set(handles.OutputForeLuminaVideo, 'Enable', 'off');
    set(handles.OutputForeChrominaVideo, 'Enable', 'off');
    set(handles.OutputForeSyncVideo, 'Enable', 'off');
    set(handles.OutputForeLumWholeVideo, 'Enable', 'off');
    set(handles.OutputForeChroWholeVideo, 'Enable', 'off');
    set(handles.OutputForeSyncWholeVideo, 'Enable', 'off');
    set(handles.OutputBackLuminaVideo, 'Enable', 'off');
    set(handles.OutputBackChrominaVideo, 'Enable', 'off');
    set(handles.OutputBackSyncVideo, 'Enable', 'off');
    set(handles.OutputBackLumWholeVideo, 'Enable', 'off');
    set(handles.OutputBackChroWholeVideo, 'Enable', 'off');
    set(handles.OutputBackSyncWholeVideo, 'Enable', 'off');
    set(handles.TargetForeSlices, 'Enable', 'off');
    set(handles.TargetForeMatteSlices, 'Enable', 'off');
    set(handles.TargetBackSlices, 'Enable', 'off');
    set(handles.TargetBackMatteSlices, 'Enable', 'off');     
    set(handles.SplitVideo, 'Enable', 'off');  
    set(handles.Recombine, 'Enable', 'off');  
    set(handles.RebuildVideo, 'Enable', 'off');
else
    set(handles.SourceVideoButton, 'Enable', UiStatus.SourceVideoButtonEnable);
    set(handles.SourceMatteButton, 'Enable', UiStatus.SourceMatteButtonEnable);
    set(handles.OpenSourceMatte, 'Enable', UiStatus.OpenSourceMatteEnable);
    set(handles.SourceSyn, 'Enable', UiStatus.SourceSynEnable);
    set(handles.TargetVideoButton, 'Enable', UiStatus.TargetVideoButtonEnable);
    set(handles.TargetMatteButton, 'Enable', UiStatus.TargetMatteButtonEnable);
    set(handles.BackVideo, 'Enable',UiStatus.BackVideoEnable);
    set(handles.TargetBackMatte, 'Enable', UiStatus.TargetBackMatteEnable);
    set(handles.OpenTargetMatte, 'Enable', UiStatus.OpenTargetMatteEnable);
    set(handles.OpenBackMatte, 'Enable', UiStatus.OpenBackMatteEnable);
    set(handles.TargetSyn, 'Enable', UiStatus.TargetSynEnable);
    set(handles.UpdateForeKeyframes, 'Enable', UiStatus.UpdateForeKeyframesEnable);
    set(handles.UpdateBackKeyframes, 'Enable', UiStatus.UpdateBackKeyframesEnable);
    set(handles.OpenForeMatteReverse, 'Enable', UiStatus.OpenForeMatteReverse);
    set(handles.OpenBackMatteReverse, 'Enable', UiStatus.OpenBackMatteReverse);
    set(handles.OpenFilter, 'Enable', UiStatus.OpenFilter);
    set(handles.SourceMatte, 'Enable', UiStatus.SourceMatte);
    set(handles.TargetForeMatte, 'Enable', UiStatus.TargetForeMatte);
    set(handles.TargetBackTag, 'Enable',UiStatus.TargetBackTag);
    set(handles.TargetBackMatteTag, 'Enable', UiStatus.TargetBackMatteTag);
    set(handles.SourceVideoMenu, 'Enable', 'on');
    set(handles.LeftAddVideoButton, 'Enable', 'on');
    set(handles.LeftPlay, 'Enable', 'on');
    set(handles.CloseLeft, 'Enable', 'on');
    set(handles.LeftKeyFrames, 'Enable', 'on');
    set(handles.RightPlay, 'Enable', 'on');
    set(handles.CloseRight, 'Enable', 'on');
    set(handles.RightKeyFrames, 'Enable', 'on');
    set(handles.TargetVideoMenu, 'Enable', 'on');
    set(handles.RightAddVideoButton, 'Enable', 'on');
    set(handles.SourceTag, 'Enable', 'on');
    set(handles.TargetForeTag, 'Enable', 'on');
    set(handles.OutputSourceVideo, 'Enable', UiStatus.OutputSourceVideo);
    set(handles.OutputSourceForeVideo, 'Enable', UiStatus.OutputSourceForeVideo);
    set(handles.OutputSourceBackVideo, 'Enable', UiStatus.OutputSourceBackVideo);
    set(handles.OutputLuminaVideo, 'Enable', UiStatus.OutputLuminaVideo);
    set(handles.OutputChrominaVideo, 'Enable', UiStatus.OutputChrominaVideo);
    set(handles.OutputSyncVideo, 'Enable', UiStatus.OutputSyncVideo);
    set(handles.OutputForeLuminaVideo, 'Enable', UiStatus.OutputForeLuminaVideo);
    set(handles.OutputForeChrominaVideo, 'Enable', UiStatus.OutputForeChrominaVideo);
    set(handles.OutputForeSyncVideo, 'Enable', UiStatus.OutputForeSyncVideo);
    set(handles.OutputForeLumWholeVideo, 'Enable', UiStatus.OutputForeLumWholeVideo);
    set(handles.OutputForeChroWholeVideo, 'Enable', UiStatus.OutputForeChroWholeVideo);
    set(handles.OutputForeSyncWholeVideo, 'Enable', UiStatus.OutputForeSyncWholeVideo);
    set(handles.OutputBackLuminaVideo, 'Enable', UiStatus.OutputBackLuminaVideo);
    set(handles.OutputBackChrominaVideo, 'Enable', UiStatus.OutputBackChrominaVideo);
    set(handles.OutputBackSyncVideo, 'Enable', UiStatus.OutputBackSyncVideo);
    set(handles.OutputBackLumWholeVideo, 'Enable', UiStatus.OutputBackLumWholeVideo);
    set(handles.OutputBackChroWholeVideo, 'Enable', UiStatus.OutputBackChroWholeVideo);
    set(handles.OutputBackSyncWholeVideo, 'Enable', UiStatus.OutputBackSyncWholeVideo);
    set(handles.TargetForeSlices, 'Enable', UiStatus.TargetForeSlices);
    set(handles.TargetForeMatteSlices, 'Enable', UiStatus.TargetForeMatteSlices);
    set(handles.TargetBackSlices, 'Enable', UiStatus.TargetBackSlices);
    set(handles.TargetBackMatteSlices, 'Enable', UiStatus.TargetBackMatteSlices);
    set(handles.SplitVideo, 'Enable', UiStatus.SplitVideo);
    set(handles.Recombine, 'Enable', UiStatus.Recombine);
    set(handles.RebuildVideo, 'Enable', 'on');
end